### PR TITLE
Fix VSCodeVim goes back to normal mode

### LINKED ISSUE #16: VIM extension: Goes back to "NORMAL" mode in case
When you use VIM plugin (vscodevim.vim) in INSERT mode and type "{{" plugin adds spaces and closing brackets, but at the same time it goes back to the NORMAL mode. Is there any way to avoid it?

### PR DESCRIPTION
**Pull request by dityaaa**
This patch should be able to fix #16, while still maintaining backward compatibility while not using VSCodeVim

### CODE REVIEW

**Comment by austenc** [comment]
Looks good, thanks! 

May I ask why you added return statements to all the `insertSnippet` calls? I'm not sure that is necessary. Please remove those and I'll merge this and send out a new release. 

Thank you!

**Comment by dityaaa** [comment]
It is necessary for the `await` operator. Without `await`, vim command will execute instantaneously, leaving cursor behind.

Without `await`
image


Using `await` to make sure snippet is fully inserted before execute vim commands
image

**Comment by austenc** [comment]
Ahh, yep, appreciate you pointing that out. This is why I shouldn't review code late at night. 😅 

Thanks again for the contribution!

**Comment by austenc** [comment]
This should be out in the latest update! Give the marketplace fifteen minutes or so to reflect the changes and let me know how it goes.

**Comment by dityaaa** [comment]
Great, now it works like a charm 😊

**Comment by AbhinavNmdo** [comment]
@dityaaa do you know the command for `append` instead of `vim_insert`?

**Pull request merged**
